// Installs a vendor package's agent files into a project's .github folder.
// Skills are linked (junction on Windows), so edits land in this tool. Instructions and prompts are
// rendered from templates with project values and copied with a "generated" header.
// Usage: codebase-context install [--dry-run] [--force] [--targets copilot,claude,codex] [--prebuilt <zip|HTTPS URL> [--sha256 <hash>] [--replace-index]]
// --force applies to instructions and skills only; --replace-index applies to the prebuilt index only.
// Targets default to config.json "targets", then ["copilot"].
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, rmdirSync, statSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';

import { PROJECT_ROOT, TOOL_ROOT, graphName } from './lib/project-root.mjs';
import { bundleContext, installBundle, readBundle } from './lib/bundles.mjs';
import { hashText, readBlock, writeBlock } from './lib/marked-block.mjs';
import { resolveTargets, skillDirsFor } from './lib/targets.mjs';

const GENERATED_MARK = 'Generated by codebase-context install';
const args = new Set(process.argv.slice(2));
const dryRun = args.has('--dry-run');
const force = args.has('--force');
const replaceIndex = args.has('--replace-index');

const values = process.argv.slice(2);
const option = (name) => {
  const index = values.indexOf(name);
  if (index < 0)
    return undefined;
  if (!values[index + 1] || values[index + 1].startsWith('--'))
    throw new Error(`${name} requires a value.`);
  return values[index + 1];
};
try {
  const source = option('--prebuilt');
  if (source) {
    const context = bundleContext(PROJECT_ROOT, option('--vendor') ?? 'exb');
    const data = await readBundle(/^https?:/i.test(source) ? source : path.resolve(PROJECT_ROOT, source), option('--sha256'));
    const result = installBundle(data, context, { replace: replaceIndex, dryRun });
    console.log(`${dryRun ? 'Validated' : 'Installed'} ${context.vendorId} ${context.version} index: ${result.files} files`);
  }
} catch (error) {
  console.error(error.message);
  process.exit(1);
}

const readJson = (file) => JSON.parse(readFileSync(file, 'utf8'));
const rel = (p) => path.relative(PROJECT_ROOT, p).replace(/\\/g, '/');
const backupRoot = path.join(PROJECT_ROOT, '.codebase-context', 'backup', new Date().toISOString().replace(/[:.]/g, '-'));
const manifestPath = path.join(PROJECT_ROOT, '.codebase-context', 'installed.json');
// Hash of each file as install last wrote it, to detect hand edits.
const installed = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : {};
const hash = (text) => createHash('sha256').update(text.replace(/\r\n/g, '\n')).digest('hex');
const log = [];
let problems = 0;

const backup = (target) => {
  const dest = path.join(backupRoot, path.relative(PROJECT_ROOT, target));
  mkdirSync(path.dirname(dest), { recursive: true });
  // Keep a copy of hand-made files before replacing them.
  statSync(target).isDirectory() ? cpSync(target, dest, { recursive: true }) : cpSync(target, dest);
  return dest;
};

const isLink = (p) => {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
};

const removeLink = (p) => {
  try {
    unlinkSync(p);
  } catch {
    rmdirSync(p);
  }
};

function linkSkill (source, target) {
  const name = path.basename(source);
  if (isLink(target)) {
    if (realpathSync(target) === realpathSync(source)) {
      log.push(`ok      skill ${name} (already linked)`);
      return;
    }
    dryRun || removeLink(target);
  } else if (existsSync(target)) {
    if (!force) {
      problems++;
      log.push(`skip    skill ${name}: ${rel(target)} is a real folder. Re-run with --force to back it up and link it.`);
      return;
    }
    if (!dryRun) {
      const saved = backup(target);
      renameSync(target, `${target}.removing`);
      rmdirSafe(`${target}.removing`);
      log.push(`backup  ${rel(target)} -> ${rel(saved)}`);
    }
  }
  dryRun || symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
  log.push(`link    skill ${name} -> ${source}`);
}

function rmdirSafe (dir) {
  for (const entry of readdirSync(dir)) {
    const p = path.join(dir, entry);
    if (isLink(p))
      removeLink(p);
    else if (statSync(p).isDirectory())
      rmdirSafe(p);
    else
      unlinkSync(p);
  }
  rmdirSync(dir);
}

function render (text, vars, header) {
  let out = text.replace(/\{\{([A-Z_]+)\}\}/g, (m, key) => (key in vars ? vars[key] : m));
  const unresolved = [...new Set(out.match(/\{\{[A-Z_]+\}\}/g) ?? [])];
  const frontmatter = out.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
  out = frontmatter
    ? `${frontmatter[0]}\n<!-- ${header} -->\n${out.slice(frontmatter[0].length)}`
    : `<!-- ${header} -->\n\n${out}`;
  return { out, unresolved };
}

function copyTemplate (source, target, vars, templateRel) {
  const name = path.basename(source);
  const key = rel(target);
  if (existsSync(target)) {
    const current = readFileSync(target, 'utf8');
    const generated = current.includes(GENERATED_MARK);
    const editedByHand = generated && installed[key] && installed[key] !== hash(current);
    if (!generated || editedByHand) {
      if (!force) {
        problems++;
        log.push(`skip    ${key}: ${generated ? 'edited by hand since the last install (move the change into the template)' : 'not generated by this tool'}. Re-run with --force to back it up and replace it.`);
        return;
      }
      dryRun || log.push(`backup  ${key} -> ${rel(backup(target))}`);
    }
  }
  const { out, unresolved } = render(readFileSync(source, 'utf8'), vars, `${GENERATED_MARK} from ${templateRel}. Edit that template, then run: npm run ai:install`);
  unresolved.length && (problems++, log.push(`warn    ${name}: unresolved ${unresolved.join(', ')}`));
  if (!dryRun) {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, out);
    installed[key] = hash(out);
  }
  log.push(`write   ${key}`);
}

function toolsGraphs () {
  const tools = path.join(PROJECT_ROOT, 'tools');
  if (!existsSync(tools))
    return '(none)';
  const names = readdirSync(tools)
    .map((n) => path.join(tools, n))
    .filter((p) => isLink(p) && existsSync(p))
    .map((p) => `\`${graphName(realpathSync(p))}\``);
  return names.length ? names.join(', ') : '(none)';
}

// Links in skill folders install no longer uses (for example after changing targets) would make Copilot list skills twice.
function removeStaleLinks (skillsDir, names) {
  for (const dir of ['.github/skills', '.claude/skills', '.agents/skills'].filter((d) => !skillDirs.includes(d))) {
    for (const name of names) {
      const target = path.join(PROJECT_ROOT, dir, name);
      if (isLink(target) && existsSync(target) && realpathSync(target) === realpathSync(path.join(skillsDir, name))) {
        dryRun || removeLink(target);
        log.push(`remove  ${dir}/${name} (not a current target folder)`);
      }
    }
  }
}

// The block is committed, so it holds no machine-specific values such as graph names.
function writeAgentsBlock (id, template, vars) {
  const key = `AGENTS.md#${id}`;
  const blockVars = { VENDOR_ROOT: vars.VENDOR_ROOT, EXB_VERSION: vars.EXB_VERSION };
  const body = template.replace(/\{\{([A-Z_]+)\}\}/g, (m, name) => (name in blockVars ? blockVars[name] : m));
  const unresolved = [...new Set(body.match(/\{\{[A-Z_]+\}\}/g) ?? [])];
  if (unresolved.length) {
    problems++;
    log.push(`warn    AGENTS.md block: unresolved ${unresolved.join(', ')}`);
    return;
  }
  const agentsPath = path.join(PROJECT_ROOT, 'AGENTS.md');
  const current = existsSync(agentsPath) ? readFileSync(agentsPath, 'utf8') : '';
  const existing = readBlock(current, id);
  if (existing !== null && installed[key] && installed[key] !== hashText(existing)) {
    if (!force) {
      problems++;
      log.push(`skip    AGENTS.md block "${id}": edited by hand since the last install (move the change into vendors/${id}/agents/AGENTS.block.md). Re-run with --force to back it up and replace it.`);
      return;
    }
    dryRun || log.push(`backup  AGENTS.md -> ${rel(backup(agentsPath))}`);
  }
  const header = `<!-- Generated by codebase-context install from vendors/${id}/agents/AGENTS.block.md. Edit that template, then run: npm run ai:install -->`;
  const content = `${header}\n${body}`;
  if (existing !== null && hashText(existing) === hashText(content)) {
    installed[key] = hashText(content);
    log.push(`ok      AGENTS.md block "${id}" (unchanged)`);
    return;
  }
  if (!dryRun) {
    writeFileSync(agentsPath, writeBlock(current, id, content));
    installed[key] = hashText(content);
  }
  log.push(`write   AGENTS.md block "${id}"${current ? '' : ' (new file)'}`);
}

// Claude Code reads AGENTS.md on its own only when no CLAUDE.md exists (and only from v2.1.277); an import works everywhere.
function writeClaudeImport () {
  const claudePath = path.join(PROJECT_ROOT, 'CLAUDE.md');
  if (!existsSync(claudePath)) {
    dryRun || writeFileSync(claudePath, '@AGENTS.md\n');
    log.push('write   CLAUDE.md (imports AGENTS.md)');
  } else if (!/^@AGENTS\.md\s*$/m.test(readFileSync(claudePath, 'utf8'))) {
    problems++;
    log.push('warn    CLAUDE.md exists without an "@AGENTS.md" line, so Claude Code will not read AGENTS.md. Add that line.');
  }
}

function writeGitignoreSection (entries) {
  const begin = '# >>> codebase-context: linked skills (generated by install, do not edit)';
  const end = '# <<< codebase-context';
  const ignorePath = path.join(PROJECT_ROOT, '.gitignore');
  const current = existsSync(ignorePath) ? readFileSync(ignorePath, 'utf8') : '';
  const eol = current.includes('\r\n') ? '\r\n' : '\n';
  const section = [begin, ...[...new Set(entries)].sort(), end].join(eol);
  const start = current.indexOf(begin);
  const stop = current.indexOf(end);
  const next = start >= 0 && stop > start
    ? current.slice(0, start) + section + current.slice(stop + end.length)
    : `${current.replace(/\s*$/, current ? eol + eol : '')}${section}${eol}`;
  if (next === current) {
    log.push('ok      .gitignore skill entries (unchanged)');
    return;
  }
  dryRun || writeFileSync(ignorePath, next);
  log.push('write   .gitignore skill entries');
}

const configPath = path.join(PROJECT_ROOT, '.codebase-context', 'config.json');
if (!existsSync(configPath)) {
  console.error(`Missing ${rel(configPath)}. Create it first (see the codebase-context README).`);
  process.exit(1);
}
const config = readJson(configPath);
const githubDir = path.join(PROJECT_ROOT, '.github');
let targets;
try {
  targets = resolveTargets(config, option('--targets'));
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
const skillDirs = skillDirsFor(targets);
const linkedSkills = [];
log.push(`targets ${targets.join(', ')} -> skills in ${skillDirs.join(', ')}`);
targets.includes('claude') && targets.includes('codex') && log.push('note    claude and codex use different skill folders; Copilot may list each skill twice');

// Backups are local safety copies, never project content.
const ignorePath = path.join(PROJECT_ROOT, '.codebase-context', '.gitignore');
if (!dryRun && !(existsSync(ignorePath) && readFileSync(ignorePath, 'utf8').split(/\r?\n/).includes('backup/'))) {
  writeFileSync(ignorePath, (existsSync(ignorePath) ? readFileSync(ignorePath, 'utf8').replace(/\s*$/, '\n') : '') + 'backup/\n');
  log.push(`write   ${rel(ignorePath)} (ignores backup/)`);
}
if (!dryRun && !readFileSync(ignorePath, 'utf8').split(/\r?\n/).includes('bundles/')) {
  writeFileSync(ignorePath, readFileSync(ignorePath, 'utf8').replace(/\s*$/, '\n') + 'bundles/\n');
}

for (const vendor of config.vendors) {
  const packageDir = vendor.package ? path.resolve(PROJECT_ROOT, vendor.package) : path.join(TOOL_ROOT, 'vendors', vendor.id);
  const pkg = readJson(path.join(packageDir, 'vendor.json'));
  const vendorRoot = path.resolve(PROJECT_ROOT, vendor.root);
  const version = existsSync(path.join(vendorRoot, pkg.version.file))
    ? String(readJson(path.join(vendorRoot, pkg.version.file))[pkg.version.path])
    : 'unknown';
  const projectGraph = graphName(PROJECT_ROOT);
  const vars = {
    PROJECT_GRAPH: projectGraph,
    VENDOR_GRAPH: graphName(vendorRoot),
    OOTB_GRAPH: `${projectGraph}-ootb-widgets`,
    TOOLS_GRAPHS: toolsGraphs(),
    VENDOR_ROOT: vendor.root.replace(/\\/g, '/'),
    EXB_VERSION: version
  };
  log.push(`${pkg.name} ${version} -> ${rel(githubDir)}${dryRun ? ' (dry run)' : ''}`);

  const skillsDir = path.join(packageDir, 'skills');
  if (existsSync(skillsDir)) {
    const names = readdirSync(skillsDir).filter((n) => existsSync(path.join(skillsDir, n, 'SKILL.md')));
    for (const dir of skillDirs) {
      dryRun || mkdirSync(path.join(PROJECT_ROOT, dir), { recursive: true });
      for (const name of names) {
        linkSkill(path.join(skillsDir, name), path.join(PROJECT_ROOT, dir, name));
        linkedSkills.push(`${dir}/${name}/`);
      }
    }
    removeStaleLinks(skillsDir, names);
  }

  const kinds = targets.includes('copilot') ? ['instructions', 'prompts'] : [];
  for (const kind of kinds) {
    const dir = path.join(packageDir, kind);
    if (!existsSync(dir))
      continue;
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.md')))
      copyTemplate(path.join(dir, file), path.join(githubDir, kind, file), vars, `vendors/${vendor.id}/${kind}/${file}`);
  }

  const blockTemplate = path.join(packageDir, 'agents', 'AGENTS.block.md');
  existsSync(blockTemplate) && writeAgentsBlock(vendor.id, readFileSync(blockTemplate, 'utf8'), vars);
}

targets.includes('claude') && writeClaudeImport();
linkedSkills.length && writeGitignoreSection(linkedSkills);

dryRun || writeFileSync(manifestPath, JSON.stringify(installed, null, 2) + '\n');
log.forEach((line) => console.log(line));
problems && console.warn(`\n${problems} item(s) need attention (see skip/warn lines).`);
process.exitCode = problems ? 1 : 0;
