// Installs a vendor package's agent files into a project's .github folder.
// Skills are linked (junction on Windows), so edits land in this tool. Instructions and prompts are
// rendered from templates with project values and copied with a "generated" header.
// Usage: codebase-context install [--dry-run] [--force] [--prebuilt <zip|HTTPS URL> [--sha256 <hash>] [--replace-index]]
// --force applies to instructions and skills only; --replace-index applies to the prebuilt index only.
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, rmdirSync, statSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';

import { PROJECT_ROOT, TOOL_ROOT, graphName } from './lib/project-root.mjs';
import { bundleContext, installBundle, readBundle } from './lib/bundles.mjs';

const GENERATED_MARK = 'Generated by codebase-context install';
const args = new Set(process.argv.slice(2));
const dryRun = args.has('--dry-run');
const force = args.has('--force');
const replaceIndex = args.has('--replace-index');

const values = process.argv.slice(2);
const option = (name) => {
  const index = values.indexOf(name);
  if (index < 0)
    return undefined;
  if (!values[index + 1] || values[index + 1].startsWith('--'))
    throw new Error(`${name} requires a value.`);
  return values[index + 1];
};
try {
  const source = option('--prebuilt');
  if (source) {
    const context = bundleContext(PROJECT_ROOT, option('--vendor') ?? 'exb');
    const data = await readBundle(/^https?:/i.test(source) ? source : path.resolve(PROJECT_ROOT, source), option('--sha256'));
    const result = installBundle(data, context, { replace: replaceIndex, dryRun });
    console.log(`${dryRun ? 'Validated' : 'Installed'} ${context.vendorId} ${context.version} index: ${result.files} files`);
  }
} catch (error) {
  console.error(error.message);
  process.exit(1);
}

const readJson = (file) => JSON.parse(readFileSync(file, 'utf8'));
const rel = (p) => path.relative(PROJECT_ROOT, p).replace(/\\/g, '/');
const backupRoot = path.join(PROJECT_ROOT, '.codebase-context', 'backup', new Date().toISOString().replace(/[:.]/g, '-'));
const manifestPath = path.join(PROJECT_ROOT, '.codebase-context', 'installed.json');
// Hash of each file as install last wrote it, to detect hand edits.
const installed = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : {};
const hash = (text) => createHash('sha256').update(text.replace(/\r\n/g, '\n')).digest('hex');
const log = [];
let problems = 0;

const backup = (target) => {
  const dest = path.join(backupRoot, path.relative(PROJECT_ROOT, target));
  mkdirSync(path.dirname(dest), { recursive: true });
  // Keep a copy of hand-made files before replacing them.
  statSync(target).isDirectory() ? cpSync(target, dest, { recursive: true }) : cpSync(target, dest);
  return dest;
};

const isLink = (p) => {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
};

const removeLink = (p) => {
  try {
    unlinkSync(p);
  } catch {
    rmdirSync(p);
  }
};

function linkSkill (source, target) {
  const name = path.basename(source);
  if (isLink(target)) {
    if (realpathSync(target) === realpathSync(source)) {
      log.push(`ok      skill ${name} (already linked)`);
      return;
    }
    dryRun || removeLink(target);
  } else if (existsSync(target)) {
    if (!force) {
      problems++;
      log.push(`skip    skill ${name}: ${rel(target)} is a real folder. Re-run with --force to back it up and link it.`);
      return;
    }
    if (!dryRun) {
      const saved = backup(target);
      renameSync(target, `${target}.removing`);
      rmdirSafe(`${target}.removing`);
      log.push(`backup  ${rel(target)} -> ${rel(saved)}`);
    }
  }
  dryRun || symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
  log.push(`link    skill ${name} -> ${source}`);
}

function rmdirSafe (dir) {
  for (const entry of readdirSync(dir)) {
    const p = path.join(dir, entry);
    if (isLink(p))
      removeLink(p);
    else if (statSync(p).isDirectory())
      rmdirSafe(p);
    else
      unlinkSync(p);
  }
  rmdirSync(dir);
}

function render (text, vars, header) {
  let out = text.replace(/\{\{([A-Z_]+)\}\}/g, (m, key) => (key in vars ? vars[key] : m));
  const unresolved = [...new Set(out.match(/\{\{[A-Z_]+\}\}/g) ?? [])];
  const frontmatter = out.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
  out = frontmatter
    ? `${frontmatter[0]}\n<!-- ${header} -->\n${out.slice(frontmatter[0].length)}`
    : `<!-- ${header} -->\n\n${out}`;
  return { out, unresolved };
}

function copyTemplate (source, target, vars, templateRel) {
  const name = path.basename(source);
  const key = rel(target);
  if (existsSync(target)) {
    const current = readFileSync(target, 'utf8');
    const generated = current.includes(GENERATED_MARK);
    const editedByHand = generated && installed[key] && installed[key] !== hash(current);
    if (!generated || editedByHand) {
      if (!force) {
        problems++;
        log.push(`skip    ${key}: ${generated ? 'edited by hand since the last install (move the change into the template)' : 'not generated by this tool'}. Re-run with --force to back it up and replace it.`);
        return;
      }
      dryRun || log.push(`backup  ${key} -> ${rel(backup(target))}`);
    }
  }
  const { out, unresolved } = render(readFileSync(source, 'utf8'), vars, `${GENERATED_MARK} from ${templateRel}. Edit that template, then run: npm run ai:install`);
  unresolved.length && (problems++, log.push(`warn    ${name}: unresolved ${unresolved.join(', ')}`));
  if (!dryRun) {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, out);
    installed[key] = hash(out);
  }
  log.push(`write   ${key}`);
}

function toolsGraphs () {
  const tools = path.join(PROJECT_ROOT, 'tools');
  if (!existsSync(tools))
    return '(none)';
  const names = readdirSync(tools)
    .map((n) => path.join(tools, n))
    .filter((p) => isLink(p) && existsSync(p))
    .map((p) => `\`${graphName(realpathSync(p))}\``);
  return names.length ? names.join(', ') : '(none)';
}

const configPath = path.join(PROJECT_ROOT, '.codebase-context', 'config.json');
if (!existsSync(configPath)) {
  console.error(`Missing ${rel(configPath)}. Create it first (see the codebase-context README).`);
  process.exit(1);
}
const config = readJson(configPath);
const githubDir = path.join(PROJECT_ROOT, '.github');

// Backups are local safety copies, never project content.
const ignorePath = path.join(PROJECT_ROOT, '.codebase-context', '.gitignore');
if (!dryRun && !(existsSync(ignorePath) && readFileSync(ignorePath, 'utf8').split(/\r?\n/).includes('backup/'))) {
  writeFileSync(ignorePath, (existsSync(ignorePath) ? readFileSync(ignorePath, 'utf8').replace(/\s*$/, '\n') : '') + 'backup/\n');
  log.push(`write   ${rel(ignorePath)} (ignores backup/)`);
}
if (!dryRun && !readFileSync(ignorePath, 'utf8').split(/\r?\n/).includes('bundles/')) {
  writeFileSync(ignorePath, readFileSync(ignorePath, 'utf8').replace(/\s*$/, '\n') + 'bundles/\n');
}

for (const vendor of config.vendors) {
  const packageDir = vendor.package ? path.resolve(PROJECT_ROOT, vendor.package) : path.join(TOOL_ROOT, 'vendors', vendor.id);
  const pkg = readJson(path.join(packageDir, 'vendor.json'));
  const vendorRoot = path.resolve(PROJECT_ROOT, vendor.root);
  const version = existsSync(path.join(vendorRoot, pkg.version.file))
    ? String(readJson(path.join(vendorRoot, pkg.version.file))[pkg.version.path])
    : 'unknown';
  const projectGraph = graphName(PROJECT_ROOT);
  const vars = {
    PROJECT_GRAPH: projectGraph,
    VENDOR_GRAPH: graphName(vendorRoot),
    OOTB_GRAPH: `${projectGraph}-ootb-widgets`,
    TOOLS_GRAPHS: toolsGraphs(),
    VENDOR_ROOT: vendor.root.replace(/\\/g, '/'),
    EXB_VERSION: version
  };
  log.push(`${pkg.name} ${version} -> ${rel(githubDir)}${dryRun ? ' (dry run)' : ''}`);

  const skillsDir = path.join(packageDir, 'skills');
  if (existsSync(skillsDir)) {
    mkdirSync(path.join(githubDir, 'skills'), { recursive: true });
    for (const name of readdirSync(skillsDir).filter((n) => existsSync(path.join(skillsDir, n, 'SKILL.md'))))
      linkSkill(path.join(skillsDir, name), path.join(githubDir, 'skills', name));
  }

  for (const kind of ['instructions', 'prompts']) {
    const dir = path.join(packageDir, kind);
    if (!existsSync(dir))
      continue;
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.md')))
      copyTemplate(path.join(dir, file), path.join(githubDir, kind, file), vars, `vendors/${vendor.id}/${kind}/${file}`);
  }
}

dryRun || writeFileSync(manifestPath, JSON.stringify(installed, null, 2) + '\n');
log.forEach((line) => console.log(line));
problems && console.warn(`\n${problems} item(s) need attention (see skip/warn lines).`);
process.exitCode = problems ? 1 : 0;
