// Installs a vendor package's agent files into a project's .github folder.
// Skills are linked (junction on Windows), so edits land in this tool. Instructions and prompts are
// rendered from templates with project values and copied with a "generated" header.
// Usage: codebase-context install [--dry-run] [--force]
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, rmdirSync, statSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { PROJECT_ROOT, TOOL_ROOT, graphName } from './lib/project-root.mjs';

const GENERATED_MARK = 'Generated by codebase-context install';
const args = new Set(process.argv.slice(2));
const dryRun = args.has('--dry-run');
const force = args.has('--force');

const readJson = (file) => JSON.parse(readFileSync(file, 'utf8'));
const rel = (p) => path.relative(PROJECT_ROOT, p).replace(/\\/g, '/');
const backupRoot = path.join(PROJECT_ROOT, '.codebase-context', 'backup', new Date().toISOString().replace(/[:.]/g, '-'));
const log = [];
let problems = 0;

const backup = (target) => {
  const dest = path.join(backupRoot, path.relative(PROJECT_ROOT, target));
  mkdirSync(path.dirname(dest), { recursive: true });
  // Keep a copy of hand-made files before replacing them.
  statSync(target).isDirectory() ? cpSync(target, dest, { recursive: true }) : cpSync(target, dest);
  return dest;
};

const isLink = (p) => {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
};

const removeLink = (p) => {
  try {
    unlinkSync(p);
  } catch {
    rmdirSync(p);
  }
};

function linkSkill (source, target) {
  const name = path.basename(source);
  if (isLink(target)) {
    if (realpathSync(target) === realpathSync(source)) {
      log.push(`ok      skill ${name} (already linked)`);
      return;
    }
    dryRun || removeLink(target);
  } else if (existsSync(target)) {
    if (!force) {
      problems++;
      log.push(`skip    skill ${name}: ${rel(target)} is a real folder. Re-run with --force to back it up and link it.`);
      return;
    }
    if (!dryRun) {
      const saved = backup(target);
      renameSync(target, `${target}.removing`);
      rmdirSafe(`${target}.removing`);
      log.push(`backup  ${rel(target)} -> ${rel(saved)}`);
    }
  }
  dryRun || symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
  log.push(`link    skill ${name} -> ${source}`);
}

function rmdirSafe (dir) {
  for (const entry of readdirSync(dir)) {
    const p = path.join(dir, entry);
    if (isLink(p))
      removeLink(p);
    else if (statSync(p).isDirectory())
      rmdirSafe(p);
    else
      unlinkSync(p);
  }
  rmdirSync(dir);
}

function render (text, vars, header) {
  let out = text.replace(/\{\{([A-Z_]+)\}\}/g, (m, key) => (key in vars ? vars[key] : m));
  const unresolved = [...new Set(out.match(/\{\{[A-Z_]+\}\}/g) ?? [])];
  const frontmatter = out.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
  out = frontmatter
    ? `${frontmatter[0]}\n<!-- ${header} -->\n${out.slice(frontmatter[0].length)}`
    : `<!-- ${header} -->\n\n${out}`;
  return { out, unresolved };
}

function copyTemplate (source, target, vars, templateRel) {
  const name = path.basename(source);
  if (existsSync(target) && !readFileSync(target, 'utf8').includes(GENERATED_MARK)) {
    if (!force) {
      problems++;
      log.push(`skip    ${rel(target)}: not generated by this tool. Re-run with --force to back it up and replace it.`);
      return;
    }
    dryRun || log.push(`backup  ${rel(target)} -> ${rel(backup(target))}`);
  }
  const { out, unresolved } = render(readFileSync(source, 'utf8'), vars, `${GENERATED_MARK} from ${templateRel}. Edit that template, then run: npm run ai:install`);
  unresolved.length && (problems++, log.push(`warn    ${name}: unresolved ${unresolved.join(', ')}`));
  if (!dryRun) {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, out);
  }
  log.push(`write   ${rel(target)}`);
}

function toolsGraphs () {
  const tools = path.join(PROJECT_ROOT, 'tools');
  if (!existsSync(tools))
    return '(none)';
  const names = readdirSync(tools)
    .map((n) => path.join(tools, n))
    .filter((p) => isLink(p) && existsSync(p))
    .map((p) => `\`${graphName(realpathSync(p))}\``);
  return names.length ? names.join(', ') : '(none)';
}

const configPath = path.join(PROJECT_ROOT, '.codebase-context', 'config.json');
if (!existsSync(configPath)) {
  console.error(`Missing ${rel(configPath)}. Create it first (see the codebase-context README).`);
  process.exit(1);
}
const config = readJson(configPath);
const githubDir = path.join(PROJECT_ROOT, '.github');

// Backups are local safety copies, never project content.
const ignorePath = path.join(PROJECT_ROOT, '.codebase-context', '.gitignore');
if (!dryRun && !(existsSync(ignorePath) && readFileSync(ignorePath, 'utf8').split(/\r?\n/).includes('backup/'))) {
  writeFileSync(ignorePath, (existsSync(ignorePath) ? readFileSync(ignorePath, 'utf8').replace(/\s*$/, '\n') : '') + 'backup/\n');
  log.push(`write   ${rel(ignorePath)} (ignores backup/)`);
}

for (const vendor of config.vendors) {
  const packageDir = vendor.package ? path.resolve(PROJECT_ROOT, vendor.package) : path.join(TOOL_ROOT, 'vendors', vendor.id);
  const pkg = readJson(path.join(packageDir, 'vendor.json'));
  const vendorRoot = path.resolve(PROJECT_ROOT, vendor.root);
  const version = existsSync(path.join(vendorRoot, pkg.version.file))
    ? String(readJson(path.join(vendorRoot, pkg.version.file))[pkg.version.path])
    : 'unknown';
  const projectGraph = graphName(PROJECT_ROOT);
  const vars = {
    PROJECT_GRAPH: projectGraph,
    VENDOR_GRAPH: graphName(vendorRoot),
    OOTB_GRAPH: `${projectGraph}-ootb-widgets`,
    TOOLS_GRAPHS: toolsGraphs(),
    VENDOR_ROOT: vendor.root.replace(/\\/g, '/'),
    EXB_VERSION: version
  };
  log.push(`${pkg.name} ${version} -> ${rel(githubDir)}${dryRun ? ' (dry run)' : ''}`);

  const skillsDir = path.join(packageDir, 'skills');
  if (existsSync(skillsDir)) {
    mkdirSync(path.join(githubDir, 'skills'), { recursive: true });
    for (const name of readdirSync(skillsDir).filter((n) => existsSync(path.join(skillsDir, n, 'SKILL.md'))))
      linkSkill(path.join(skillsDir, name), path.join(githubDir, 'skills', name));
  }

  for (const kind of ['instructions', 'prompts']) {
    const dir = path.join(packageDir, kind);
    if (!existsSync(dir))
      continue;
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.md')))
      copyTemplate(path.join(dir, file), path.join(githubDir, kind, file), vars, `vendors/${vendor.id}/${kind}/${file}`);
  }
}

log.forEach((line) => console.log(line));
problems && console.warn(`\n${problems} item(s) need attention (see skip/warn lines).`);
process.exitCode = problems ? 1 : 0;
