// Runs vendor and project fact probes, writes versioned results, and reports changes.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { runProbe } from './probes.mjs';

const readJson = (file) => JSON.parse(readFileSync(file, 'utf8'));

const compareVersions = (a, b) => {
  const pa = a.split(/[.-]/).map((n) => Number.parseInt(n, 10) || 0);
  const pb = b.split(/[.-]/).map((n) => Number.parseInt(n, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (d)
      return d;
  }
  return 0;
};

const short = (value) => {
  const text = typeof value === 'string' ? value : JSON.stringify(value);
  return text === undefined ? '' : text.length > 160 ? `${text.slice(0, 157)}...` : text;
};

const cell = (text) => String(text ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

export function runFacts (probes, roots) {
  return Object.fromEntries(probes.map((probe) => [probe.id, runProbe(probe, roots)]));
}

export function diffFacts (before, after) {
  const changes = [];
  for (const id of new Set([...Object.keys(before), ...Object.keys(after)])) {
    const a = before[id];
    const b = after[id];
    if (!a)
      changes.push({ id, change: 'added', section: b.section, after: b.value });
    else if (!b)
      changes.push({ id, change: 'removed', section: a.section, before: a.value });
    else if (a.status !== b.status)
      changes.push({ id, change: `status ${a.status} -> ${b.status}`, section: b.section, before: a.value, after: b.value });
    else if (JSON.stringify(a.value) !== JSON.stringify(b.value))
      changes.push({ id, change: 'value', section: b.section, before: a.value, after: b.value });
  }
  return changes;
}

export function factsMarkdown (title, facts) {
  const bySection = {};
  for (const [id, fact] of Object.entries(facts))
    (bySection[fact.section ?? 'other'] ??= []).push([id, fact]);

  const lines = [`# ${title}`, '', 'Generated by codebase-context (`knowledge facts`). Do not edit.', ''];
  for (const [section, rows] of Object.entries(bySection)) {
    lines.push(`## ${section}`, '', '| Fact | Status | Value | Source |', '| --- | --- | --- | --- |');
    rows.forEach(([id, f]) => lines.push(`| \`${id}\` | ${f.status} | ${cell(short(f.value ?? f.error))} | \`${cell(f.source)}\` |`));
    lines.push('');
  }
  return lines.join('\n');
}

export function changesMarkdown (title, changes) {
  const lines = [`# ${title}`, ''];
  if (!changes.length)
    return [...lines, 'No changes.', ''].join('\n');
  lines.push('Review the reference file named in "Section" for each change.', '', '| Fact | Section | Change | Before | After |', '| --- | --- | --- | --- | --- |');
  changes.forEach((c) => lines.push(`| \`${c.id}\` | ${c.section ?? ''} | ${c.change} | ${cell(short(c.before))} | ${cell(short(c.after))} |`));
  return [...lines, ''].join('\n');
}

// Writes <out>/facts/<version>.json and .md, and a changes report against the same version's last run or the newest older version.
export function writeVendorFacts ({ vendorId, version, facts, outDir }) {
  const dir = path.join(outDir, 'facts');
  mkdirSync(dir, { recursive: true });
  const jsonPath = path.join(dir, `${version}.json`);

  let baseline = null;
  let baselineLabel = null;
  if (existsSync(jsonPath)) {
    baseline = readJson(jsonPath).facts;
    baselineLabel = `${version} (previous run)`;
  } else {
    const older = readdirSync(dir)
      .filter((f) => /^\d[\w.-]*\.json$/.test(f))
      .map((f) => f.replace(/\.json$/, ''))
      .filter((v) => compareVersions(v, version) < 0)
      .sort(compareVersions)
      .pop();
    if (older) {
      baseline = readJson(path.join(dir, `${older}.json`)).facts;
      baselineLabel = older;
    }
  }

  writeFileSync(jsonPath, JSON.stringify({ vendor: vendorId, version, generatedAt: new Date().toISOString(), facts }, null, 2));
  writeFileSync(path.join(dir, `${version}.md`), factsMarkdown(`${vendorId} ${version} facts`, facts));

  const changes = baseline ? diffFacts(baseline, facts) : [];
  baseline && writeFileSync(path.join(dir, `changes-${version}.md`), changesMarkdown(`${vendorId}: changes from ${baselineLabel} to ${version}`, changes));
  return { jsonPath, baselineLabel, changes };
}

export function writeProjectFacts ({ facts, outDir }) {
  mkdirSync(outDir, { recursive: true });
  const jsonPath = path.join(outDir, 'facts.json');
  const before = existsSync(jsonPath) ? readJson(jsonPath).facts : null;
  writeFileSync(jsonPath, JSON.stringify({ generatedAt: new Date().toISOString(), facts }, null, 2));
  writeFileSync(path.join(outDir, 'facts.md'), factsMarkdown('Project facts', facts));
  return { jsonPath, changes: before ? diffFacts(before, facts) : [] };
}
